/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Child: typeof import('./src/components/child.vue')['default']
    Child1: typeof import('./src/components/child1.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    ImportData: typeof import('./src/components/importData.vue')['default']
    JsonData: typeof import('./src/components/JsonData.vue')['default']
    JsonDataChild: typeof import('./src/components/JsonDataChild.vue')['default']
    JsonDataParent: typeof import('./src/components/JsonDataParent.vue')['default']
    JsonFlowChart: typeof import('./src/components/JsonFlowChart.vue')['default']
    JsonTableDemo: typeof import('./src/components/JsonTableDemo.vue')['default']
    JsonVisualizer: typeof import('./src/components/JsonVisualizer.vue')['default']
    Parent: typeof import('./src/components/parent.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Tree: typeof import('primevue/tree')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
